name: reviewdog
on:
  pull_request:
    paths:
    - '**.go'
    - '.github/workflows/reviewdog.yml'

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install golint
        run: go -u get golang.org/x/lint/golint
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-check -runners=golint,govet
